<template>
  <div id="JJCK" class="app-container calendar-list-container">
    <el-row style="margin-bottom:10px;">
      <el-col :xs="5" :sm="5" :md="5" :lg="4" :xl="3">
        <el-input placeholder="请输入工厂" style="width:95%;" size="mini" clearable></el-input>
      </el-col>
      <el-col :xs="5" :sm="5" :md="5" :lg="4" :xl="3">
        <el-date-picker type="datetime" placeholder="选择日期时间段" size="mini" style="width:90%"></el-date-picker>
      </el-col>
      <el-col :xs="5" :sm="5" :md="5" :lg="4" :xl="3">
        <el-button type="primary" icon="el-icon-search" size="mini">查询</el-button>
      </el-col>
    </el-row>
    <el-row>
      <el-col :xs="24" :sm="24" :md="24" :lg="24" :xl="24">
        <el-table
          size="mini"
          :data="goods"
          :header-cell-class-name="tableRowClassName"
          v-loading="listloading"
          element-loading-text="给我一点时间"
          border
          fit
          highlight-current-row
          style="width: 100%"
        >
        <el-table-column label="序号" prop="non" fixed width="100px"></el-table-column>
          <el-table-column label="出库通知单号" prop="ZCKTZD" fixed width="150px"></el-table-column>
          <el-table-column label="出库通知单行号" prop="ZCITEM" width="150px"></el-table-column>
          <el-table-column label="工厂" prop="WERKS"></el-table-column>
          <el-table-column label="供应商或债权人的帐号" prop="LIFNR" width="170px"></el-table-column>
          <el-table-column label="转储单的供应(发出)工厂" prop="RESWK" width="170px"></el-table-column>
          <el-table-column label="库存地点" prop="GRUND" width="150px"></el-table-column>
          <el-table-column label="预留/相关需求的编号" prop="RSNUM" width="150px"></el-table-column>
          <el-table-column label="预留/相关需求的项目编号" prop="RSPOS" width="170px"></el-table-column>
          <el-table-column label="领料单行项目" prop="ZLDITEM" width="150px"></el-table-column>
          <el-table-column label="订单类型（采购）" width="150px" prop="BSART"></el-table-column>
          <el-table-column label="采购凭证号" prop="EBELN" width="150px"></el-table-column>
          <el-table-column label="采购凭证的项目编号" prop="EBELP" width="150px"></el-table-column>
          <el-table-column label="转储单编号" prop="TANUM" width="150px"></el-table-column>
          <el-table-column label="转储单项目" prop="TAPOS" width="150px"></el-table-column>
          <el-table-column label="销售凭证" prop="VBELN_SO" width="150px"></el-table-column>
          <el-table-column label="转储单项目" prop="POSNR" width="150px"></el-table-column>
          <el-table-column label="销售凭证项目" prop="TAPOS" width="150px"></el-table-column>
          <el-table-column label="交货" prop="VBELN" width="150px"></el-table-column>
          <el-table-column label="交货项目" prop="VBELP" width="150px"></el-table-column>
          <el-table-column label="计划单号" prop="ZSEQU" width="150px"></el-table-column>
          <el-table-column label="采购申请编号" prop="BANFN" width="150px"></el-table-column>
          <el-table-column label="采购申请的项目编号" prop="BNFPO" width="150px"></el-table-column>
          <el-table-column label="物料编号" prop="MATNR" width="150px"></el-table-column>
          <el-table-column label="物料组" prop="MATKL" width="150px"></el-table-column>
          <el-table-column label="发货数量" prop="ZFHSL" width="150px"></el-table-column>
          <el-table-column label="发货数量" prop="ZSJFHSL" width="150px"></el-table-column>
          <el-table-column label="计量单位" prop="MEINS" width="150px"></el-table-column>
          <el-table-column label="移动类型（库存管理）" prop="BWART" width="150px"></el-table-column>
          <el-table-column label="库存地点" prop="LGORT" width="170px"></el-table-column>
          <el-table-column label="创建对象的人员名称" prop="ZCJR" width="170px"></el-table-column>
          <el-table-column label="记录的创建日期" prop="ZCJRQ" width="170px"></el-table-column>
          <el-table-column label="输入时间" prop="CJSJ" width="170px"></el-table-column>
          <el-table-column label="采购申请编号" prop="ZBAN1" width="170px"></el-table-column>
          <el-table-column label="采购申请的项目编号" prop="ZBNF1" width="170px"></el-table-column>
          <el-table-column label="仓库号/混合仓库 " prop="LGNUM" width="170px"></el-table-column>
          <el-table-column label="物料凭证编号" prop="MBLNR" width="150px"></el-table-column>
          <el-table-column label="物料凭证中的项目" prop="ZEILE" width="150px"></el-table-column>
          <el-table-column label="凭证中的过账日期" prop="BUDAT" width="150px"></el-table-column>
          <el-table-column label="数量" prop="ZDGZSL" width="150px"></el-table-column>
          <el-table-column label="退货项目" prop="ZTKBS" width="150px"></el-table-column>
          <el-table-column label="代储代销标识" prop="ZDCDX" width="150px"></el-table-column>
          <el-table-column label="创建类型" prop="ZCJLX" width="150px"></el-table-column>
        </el-table>
        <el-pagination
          background
          @size-change="handleSizeChange"
          @current-change="handleCurrentChange"
          :current-page="1"
          :page-sizes="[10,20,30, 50]"
          :page-size="1"
          layout="total, sizes, prev, pager, next, jumper"
          :total="15"
          style="text-align: center;"
        ></el-pagination>
      </el-col>
    </el-row>
  </div>
</template>

<script>
export default {
  name: "JJCK",
  data() {
    return {
      listloading: false,
      goods: [
                   {
                     non:1,
          ZCKTZD: "2-20170203-000344",
          ZCITEM: 1,
          WERKS: "C264",
          LIFNR: "VC177",
          RESWK: "15G1",
          GRUND: "",
          RSNUM: 0,
          RSPOS: 0,
          ZLDITEM: 0,
          BSART: "X015",
          EBELN: "4700148701",
          EBELP: 10,
          TANUM: 0,
          TAPOS: 0,
          VBELN_SO: "",
          POSNR: 0,
          TAPOS: "",
          VBELN: 0,
          VBELP: "",
          ZSEQU: "2019012100001",
          BANFN: "30372765",
          BNFPO: 10,
          MATNR: "90874643872",
          MATKL: "3020333",
          ZFHSL: 6.2,
          ZSJFHSL: 0,
          MEINS: "T0",
          BWART: 643,
          LGORT: "C273",
          ZCJR: "80363165",
          ZCJRQ: "20190503",
          CJSJ: "92845",
          ZBAN1: "",
          ZBNF1: "",
          LGNUM: "",
          MBLNR: "",
          ZEILE: 0,
          BUDAT: 0,
          ZDGZSL: 0,
          ZTKBS: "",
          ZDCDX: "",
          ZCJLX: "4"
        },
           {
             non:2,
          ZCKTZD: "2-20170203-000321",
          ZCITEM: 1,
          WERKS: "C264",
          LIFNR: "VC877",
          RESWK: "15G1",
          GRUND: "",
          RSNUM: 0,
          RSPOS: 0,
          ZLDITEM: 0,
          BSART: "X015",
          EBELN: "4700148701",
          EBELP: 10,
          TANUM: 0,
          TAPOS: 0,
          VBELN_SO: "",
          POSNR: 0,
          TAPOS: "",
          VBELN: 0,
          VBELP: "",
          ZSEQU: "2019012100001",
          BANFN: "30372765",
          BNFPO: 10,
          MATNR: "90874643872",
          MATKL: "3020333",
          ZFHSL: 6.2,
          ZSJFHSL: 0,
          MEINS: "T0",
          BWART: 643,
          LGORT: "C273",
          ZCJR: "80363165",
          ZCJRQ: "20190503",
          CJSJ: "92845",
          ZBAN1: "",
          ZBNF1: "",
          LGNUM: "",
          MBLNR: "",
          ZEILE: 0,
          BUDAT: 0,
          ZDGZSL: 0,
          ZTKBS: "",
          ZDCDX: "",
          ZCJLX: "4"
        },
                {
                  non:3,
          ZCKTZD: "2-20170203-000310",
          ZCITEM: 1,
          WERKS: "C264",
          LIFNR: "VC273",
          RESWK: "15G1",
          GRUND: "",
          RSNUM: 0,
          RSPOS: 0,
          ZLDITEM: 0,
          BSART: "X015",
          EBELN: "4700148701",
          EBELP: 10,
          TANUM: 0,
          TAPOS: 0,
          VBELN_SO: "",
          POSNR: 0,
          TAPOS: "",
          VBELN: 0,
          VBELP: "",
          ZSEQU: "2017012100001",
          BANFN: "30372765",
          BNFPO: 10,
          MATNR: "11004643872",
          MATKL: "3020333",
          ZFHSL: 6.2,
          ZSJFHSL: 0,
          MEINS: "T0",
          BWART: 643,
          LGORT: "C273",
          ZCJR: "80363165",
          ZCJRQ: "20190203",
          CJSJ: "92855",
          ZBAN1: "",
          ZBNF1: "",
          LGNUM: "",
          MBLNR: "",
          ZEILE: 0,
          BUDAT: 0,
          ZDGZSL: 0,
          ZTKBS: "",
          ZDCDX: "",
          ZCJLX: "4"
        },
           {
             non:4,
          ZCKTZD: "2-20170203-000976",
          ZCITEM: 1,
          WERKS: "C267",
          LIFNR: "VC273",
          RESWK: "15G2",
          GRUND: "",
          RSNUM: 0,
          RSPOS: 0,
          ZLDITEM: 0,
          BSART: "X015",
          EBELN: "4700148701",
          EBELP: 10,
          TANUM: 0,
          TAPOS: 0,
          VBELN_SO: "",
          POSNR: 0,
          TAPOS: "",
          VBELN: 0,
          VBELP: "",
          ZSEQU: "2018012100001",
          BANFN: "30372765",
          BNFPO: 10,
          MATNR: "11004643872",
          MATKL: "3020333",
          ZFHSL: 6.2,
          ZSJFHSL: 0,
          MEINS: "T0",
          BWART: 643,
          LGORT: "C273",
          ZCJR: "80363165",
          ZCJRQ: "20190207",
          CJSJ: "92855",
          ZBAN1: "",
          ZBNF1: "",
          LGNUM: "",
          MBLNR: "",
          ZEILE: 0,
          BUDAT: 0,
          ZDGZSL: 0,
          ZTKBS: "",
          ZDCDX: "",
          ZCJLX: "3"
        },
           {
             non:5,
          ZCKTZD: "2-20170203-000344",
          ZCITEM: 1,
          WERKS: "C264",
          LIFNR: "VC277",
          RESWK: "15G1",
          GRUND: "",
          RSNUM: 0,
          RSPOS: 0,
          ZLDITEM: 0,
          BSART: "X015",
          EBELN: "4700148701",
          EBELP: 10,
          TANUM: 0,
          TAPOS: 0,
          VBELN_SO: "",
          POSNR: 0,
          TAPOS: "",
          VBELN: 0,
          VBELP: "",
          ZSEQU: "2019012100001",
          BANFN: "30372765",
          BNFPO: 10,
          MATNR: "90874643872",
          MATKL: "3020333",
          ZFHSL: 6.2,
          ZSJFHSL: 0,
          MEINS: "T0",
          BWART: 643,
          LGORT: "C273",
          ZCJR: "80363165",
          ZCJRQ: "20190503",
          CJSJ: "92845",
          ZBAN1: "",
          ZBNF1: "",
          LGNUM: "",
          MBLNR: "",
          ZEILE: 0,
          BUDAT: 0,
          ZDGZSL: 0,
          ZTKBS: "",
          ZDCDX: "",
          ZCJLX: "4"
        },
                {
                  non:6,
          ZCKTZD: "2-20170203-000315",
          ZCITEM: 1,
          WERKS: "C264",
          LIFNR: "VC273",
          RESWK: "15G1",
          GRUND: "",
          RSNUM: 0,
          RSPOS: 0,
          ZLDITEM: 0,
          BSART: "X015",
          EBELN: "4700148701",
          EBELP: 10,
          TANUM: 0,
          TAPOS: 0,
          VBELN_SO: "",
          POSNR: 0,
          TAPOS: "",
          VBELN: 0,
          VBELP: "",
          ZSEQU: "2017012100001",
          BANFN: "30372765",
          BNFPO: 10,
          MATNR: "11004643872",
          MATKL: "3020333",
          ZFHSL: 6.2,
          ZSJFHSL: 0,
          MEINS: "T0",
          BWART: 643,
          LGORT: "C273",
          ZCJR: "80363165",
          ZCJRQ: "20190203",
          CJSJ: "92855",
          ZBAN1: "",
          ZBNF1: "",
          LGNUM: "",
          MBLNR: "",
          ZEILE: 0,
          BUDAT: 0,
          ZDGZSL: 0,
          ZTKBS: "",
          ZDCDX: "",
          ZCJLX: "4"
        },
        {
          non:7,
          ZCKTZD: "2-20170203-00032",
          ZCITEM: 1,
          WERKS: "C274",
          LIFNR: "VC274",
          RESWK: "15G1",
          GRUND: "",
          RSNUM: 0,
          RSPOS: 0,
          ZLDITEM: 0,
          BSART: "X015",
          EBELN: "4700148701",
          EBELP: 10,
          TANUM: 0,
          TAPOS: 0,
          VBELN_SO: "",
          POSNR: 0,
          TAPOS: "",
          VBELN: 0,
          VBELP: "",
          ZSEQU: "2017012300001",
          BANFN: "30372765",
          BNFPO: 10,
          MATNR: "11004643866",
          MATKL: "3020333",
          ZFHSL: 9.8,
          ZSJFHSL: 0,
          MEINS: "T0",
          BWART: 643,
          LGORT: "C271",
          ZCJR: "80363165",
          ZCJRQ: "20170203",
          CJSJ: "92855",
          ZBAN1: "",
          ZBNF1: "",
          LGNUM: "",
          MBLNR: "",
          ZEILE: 0,
          BUDAT: 0,
          ZDGZSL: 0,
          ZTKBS: "",
          ZDCDX: "",
          ZCJLX: "4"
        },
           {
             non:8,
          ZCKTZD: "2-20170203-000344",
          ZCITEM: 1,
          WERKS: "C264",
          LIFNR: "VC277",
          RESWK: "15G1",
          GRUND: "",
          RSNUM: 0,
          RSPOS: 0,
          ZLDITEM: 0,
          BSART: "X015",
          EBELN: "4700148701",
          EBELP: 10,
          TANUM: 0,
          TAPOS: 0,
          VBELN_SO: "",
          POSNR: 0,
          TAPOS: "",
          VBELN: 0,
          VBELP: "",
          ZSEQU: "2019012100001",
          BANFN: "30372765",
          BNFPO: 10,
          MATNR: "90874643872",
          MATKL: "3020333",
          ZFHSL: 6.2,
          ZSJFHSL: 0,
          MEINS: "T0",
          BWART: 643,
          LGORT: "C273",
          ZCJR: "80363165",
          ZCJRQ: "20190503",
          CJSJ: "92845",
          ZBAN1: "",
          ZBNF1: "",
          LGNUM: "",
          MBLNR: "",
          ZEILE: 0,
          BUDAT: 0,
          ZDGZSL: 0,
          ZTKBS: "",
          ZDCDX: "",
          ZCJLX: "4"
        },
         {
           non:9,
          ZCKTZD: "2-20170203-000321",
          ZCITEM: 1,
          WERKS: "C264",
          LIFNR: "VC277",
          RESWK: "15G1",
          GRUND: "",
          RSNUM: 0,
          RSPOS: 0,
          ZLDITEM: 0,
          BSART: "X015",
          EBELN: "4700148701",
          EBELP: 10,
          TANUM: 0,
          TAPOS: 0,
          VBELN_SO: "",
          POSNR: 0,
          TAPOS: "",
          VBELN: 0,
          VBELP: "",
          ZSEQU: "2019012100001",
          BANFN: "30372765",
          BNFPO: 10,
          MATNR: "90874643872",
          MATKL: "3020333",
          ZFHSL: 6.2,
          ZSJFHSL: 0,
          MEINS: "T0",
          BWART: 643,
          LGORT: "C273",
          ZCJR: "80363165",
          ZCJRQ: "20190503",
          CJSJ: "92845",
          ZBAN1: "",
          ZBNF1: "",
          LGNUM: "",
          MBLNR: "",
          ZEILE: 0,
          BUDAT: 0,
          ZDGZSL: 0,
          ZTKBS: "",
          ZDCDX: "",
          ZCJLX: "4"
        },
                {
                  non:10,
          ZCKTZD: "2-20170203-000310",
          ZCITEM: 1,
          WERKS: "C264",
          LIFNR: "VC273",
          RESWK: "15G1",
          GRUND: "",
          RSNUM: 0,
          RSPOS: 0,
          ZLDITEM: 0,
          BSART: "X015",
          EBELN: "4700148701",
          EBELP: 10,
          TANUM: 0,
          TAPOS: 0,
          VBELN_SO: "",
          POSNR: 0,
          TAPOS: "",
          VBELN: 0,
          VBELP: "",
          ZSEQU: "2017012100001",
          BANFN: "30372765",
          BNFPO: 10,
          MATNR: "11004643872",
          MATKL: "3020333",
          ZFHSL: 6.2,
          ZSJFHSL: 0,
          MEINS: "T0",
          BWART: 643,
          LGORT: "C273",
          ZCJR: "80363165",
          ZCJRQ: "20190203",
          CJSJ: "92855",
          ZBAN1: "",
          ZBNF1: "",
          LGNUM: "",
          MBLNR: "",
          ZEILE: 0,
          BUDAT: 0,
          ZDGZSL: 0,
          ZTKBS: "",
          ZDCDX: "",
          ZCJLX: "4"
        },
           {
             non:11,
          ZCKTZD: "2-20170203-000976",
          ZCITEM: 1,
          WERKS: "C267",
          LIFNR: "VC273",
          RESWK: "15G2",
          GRUND: "",
          RSNUM: 0,
          RSPOS: 0,
          ZLDITEM: 0,
          BSART: "X015",
          EBELN: "4700148701",
          EBELP: 10,
          TANUM: 0,
          TAPOS: 0,
          VBELN_SO: "",
          POSNR: 0,
          TAPOS: "",
          VBELN: 0,
          VBELP: "",
          ZSEQU: "2018012100001",
          BANFN: "30372765",
          BNFPO: 10,
          MATNR: "11004643872",
          MATKL: "3020333",
          ZFHSL: 6.2,
          ZSJFHSL: 0,
          MEINS: "T0",
          BWART: 643,
          LGORT: "C273",
          ZCJR: "80363165",
          ZCJRQ: "20190207",
          CJSJ: "92855",
          ZBAN1: "",
          ZBNF1: "",
          LGNUM: "",
          MBLNR: "",
          ZEILE: 0,
          BUDAT: 0,
          ZDGZSL: 0,
          ZTKBS: "",
          ZDCDX: "",
          ZCJLX: "3"
        },
           {
             non:12,
          ZCKTZD: "2-20170203-000344",
          ZCITEM: 1,
          WERKS: "C264",
          LIFNR: "VC277",
          RESWK: "15G1",
          GRUND: "",
          RSNUM: 0,
          RSPOS: 0,
          ZLDITEM: 0,
          BSART: "X015",
          EBELN: "4700148701",
          EBELP: 10,
          TANUM: 0,
          TAPOS: 0,
          VBELN_SO: "",
          POSNR: 0,
          TAPOS: "",
          VBELN: 0,
          VBELP: "",
          ZSEQU: "2019012100001",
          BANFN: "30372765",
          BNFPO: 10,
          MATNR: "90874643872",
          MATKL: "3020333",
          ZFHSL: 6.2,
          ZSJFHSL: 0,
          MEINS: "T0",
          BWART: 643,
          LGORT: "C273",
          ZCJR: "80363165",
          ZCJRQ: "20190503",
          CJSJ: "92845",
          ZBAN1: "",
          ZBNF1: "",
          LGNUM: "",
          MBLNR: "",
          ZEILE: 0,
          BUDAT: 0,
          ZDGZSL: 0,
          ZTKBS: "",
          ZDCDX: "",
          ZCJLX: "4"
        },
                {
                  non:13,
          ZCKTZD: "2-20170203-000315",
          ZCITEM: 1,
          WERKS: "C264",
          LIFNR: "VC273",
          RESWK: "15G1",
          GRUND: "",
          RSNUM: 0,
          RSPOS: 0,
          ZLDITEM: 0,
          BSART: "X015",
          EBELN: "4700148701",
          EBELP: 10,
          TANUM: 0,
          TAPOS: 0,
          VBELN_SO: "",
          POSNR: 0,
          TAPOS: "",
          VBELN: 0,
          VBELP: "",
          ZSEQU: "2017012100001",
          BANFN: "30372765",
          BNFPO: 10,
          MATNR: "11004643872",
          MATKL: "3020333",
          ZFHSL: 6.2,
          ZSJFHSL: 0,
          MEINS: "T0",
          BWART: 643,
          LGORT: "C273",
          ZCJR: "80363165",
          ZCJRQ: "20190203",
          CJSJ: "92855",
          ZBAN1: "",
          ZBNF1: "",
          LGNUM: "",
          MBLNR: "",
          ZEILE: 0,
          BUDAT: 0,
          ZDGZSL: 0,
          ZTKBS: "",
          ZDCDX: "",
          ZCJLX: "4"
        },
           {
             non:14,
          ZCKTZD: "2-20170203-000344",
          ZCITEM: 1,
          WERKS: "C264",
          LIFNR: "VC277",
          RESWK: "15G1",
          GRUND: "",
          RSNUM: 0,
          RSPOS: 0,
          ZLDITEM: 0,
          BSART: "X015",
          EBELN: "4700148701",
          EBELP: 10,
          TANUM: 0,
          TAPOS: 0,
          VBELN_SO: "",
          POSNR: 0,
          TAPOS: "",
          VBELN: 0,
          VBELP: "",
          ZSEQU: "2019012100001",
          BANFN: "30372765",
          BNFPO: 10,
          MATNR: "90874643872",
          MATKL: "3020333",
          ZFHSL: 6.2,
          ZSJFHSL: 0,
          MEINS: "T0",
          BWART: 643,
          LGORT: "C273",
          ZCJR: "80363165",
          ZCJRQ: "20190503",
          CJSJ: "92845",
          ZBAN1: "",
          ZBNF1: "",
          LGNUM: "",
          MBLNR: "",
          ZEILE: 0,
          BUDAT: 0,
          ZDGZSL: 0,
          ZTKBS: "",
          ZDCDX: "",
          ZCJLX: "4"
        },
                {
                  non:15,
          ZCKTZD: "2-20170203-000315",
          ZCITEM: 1,
          WERKS: "C264",
          LIFNR: "VC273",
          RESWK: "15G1",
          GRUND: "",
          RSNUM: 0,
          RSPOS: 0,
          ZLDITEM: 0,
          BSART: "X015",
          EBELN: "4700148701",
          EBELP: 10,
          TANUM: 0,
          TAPOS: 0,
          VBELN_SO: "",
          POSNR: 0,
          TAPOS: "",
          VBELN: 0,
          VBELP: "",
          ZSEQU: "2017012100001",
          BANFN: "30372765",
          BNFPO: 10,
          MATNR: "11004643872",
          MATKL: "3020333",
          ZFHSL: 6.2,
          ZSJFHSL: 0,
          MEINS: "T0",
          BWART: 643,
          LGORT: "C273",
          ZCJR: "80363165",
          ZCJRQ: "20190203",
          CJSJ: "92855",
          ZBAN1: "",
          ZBNF1: "",
          LGNUM: "",
          MBLNR: "",
          ZEILE: 0,
          BUDAT: 0,
          ZDGZSL: 0,
          ZTKBS: "",
          ZDCDX: "",
          ZCJLX: "4"
        }, {
                  non:'合计',
          ZCKTZD: "",
          ZCITEM: '',
          WERKS: "",
          LIFNR: "",
          RESWK: "",
          GRUND: "",
          RSNUM: '',
          RSPOS: '',
          ZLDITEM: '',
          BSART: "",
          EBELN: "",
          EBELP: '',
          TANUM: '',
          TAPOS: '',
          VBELN_SO: "",
          POSNR: '',
          TAPOS: "",
          VBELN: '',
          VBELP: "",
          ZSEQU: "",
          BANFN: "",
          BNFPO: 10,
          MATNR: "",
          MATKL: "",
          ZFHSL: 0,
          ZSJFHSL: 0,
          MEINS: "",
          BWART: '',
          LGORT: "",
          ZCJR: "",
          ZCJRQ: "",
          CJSJ: "",
          ZBAN1: "",
          ZBNF1: "",
          LGNUM: "",
          MBLNR: "",
          ZEILE: '',
          BUDAT: '',
          ZDGZSL: 0,
          ZTKBS: "",
          ZDCDX: "",
          ZCJLX: ""
        }
      ]
    };
  },

  methods: {
    tableRowClassName({ row, rowIndex }) {
      // 表头行的 className 的回调方法，也可以使用字符串为所有表头行设置一个固定的 className。
      if (rowIndex === 0) {
        return "el-button--primary is-active"; // 'warning-row'
      } // 'el-button--primary is-plain'// 'warning-row'
      return "";
    },
    handleSizeChange() {},
    handleCurrentChange() {}
  }
};
</script>



<style lang="scss" scoped>
</style>


